openapi: 3.0.0
info:
  title: Tasker Service Api
  description: Manages tasks and their ads
  version: 0.0.1
servers: 
    - url: http://localhost:7979
      description: Local dev server
paths:
  /tasks/:
    post:
      summary: Creates a new task entry with given info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: task created
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Task'
        '400':
          description: Invalid request syntax.
        '422':
          description: Incomplete book information. Some required fields missing.
    get:
      summary: Retrieves all task entries 
      responses:
        '200':
          description: all task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          
  /task/{id}:
    get:
      summary: Retrieves the entry for the task with the given ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the task to retrieve
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: task object matching given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
                
    delete:
      summary: Deletes the entry for the task with the given ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the tasks to delete
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: task successfully deleted
    put:
      summary: Updated the entry for the task with the given ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the task you would like to update
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: book successfully updated.
        '422':
          description: task on path mush match the ID in the task object
   
  /task/category/{category}:
    get:
      summary: Retrieves the entry for the task with the given category
      parameters:
        - name: category
          in: path
          required: true
          description: ID of the note to retrieve
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: note object matching given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
                
components:
  schemas:
    Task:
      properties:
        id:
          type: integer
        description:
          type: string
        createDate:
          type: object
        dueDate:
          type: object
        category:
          type: string

        
        
        
        