openapi: 3.0.0
info:
  title: Word API
  description: A simple service that returns a random word and it's definition
  version: 0.0.1
servers: 
    - url: http://localhost:8080
      description: Local dev server
paths:
  /word/:
    get:
      summary: returns a word
      description: generates a random number and returns the word associated with that number
      responses:
        '200':
          description: word and correspoding definition
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Word'
components:
  schemas:
    Word:
      properties:
        word:
          type: string
        definition: 
          type: string