openapi: 3.0.0
info:
  title: Rest Calculator
  description: A simple service that echoes your input back to you as a string of corresponding month
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: local dev server
paths:
  /add/:
    post:
      summary: adds two numbers and returns sum
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Calc'
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: object
      
        '422':
          description: Incomplete or invalid input
  /mult/:
    post:
      summary: multiplies two numbers and returns sum
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Calc'
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: object
      
        '422':
          description: Incomplete or invalid input

  /subtract/:
    post:
      summary: subtracts two numbers and returns sum
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Calc'
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: object
      
        '422':
          description: Incomplete or invalid input
          
  /divide/:
    post:
      summary: divides two numbers and returns sum
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Calc'
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: object
      
        '422':
          description: Incomplete or invalid input
          
          
components:
  schemas:
    Calc:
      properties:
        operand1:
          type: integer
        operand2:
          type: integer
      example: 
        operand1: 5
        operand2: 7