openapi: 3.0.0
info:
  title: Echo Service
  description: A simple service that echoes your input back to you
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: local dev server
paths:
  /day/{dayNumber}:
    get:
      summary: echoes back a number
      description: converts input number to day string
      parameters: 
      - name: dayNumber
        in: path
        required: true
        description: the value for the day you would like echoed back to you
        schema:
          type: integer
          format: int64
          minimum: 1
          maximum: 7
      responses:
        '200':
          description: the corresponding day
          content:
            application/json:
              schema:
                type: string
        '422':
          description: you must enter a number between 1 and 7
      