openapi: 3.0.0
info:
  title: helloRestService-Talford-Albert.yaml
  description: A simple service that echos your input back to you.
  version: 0.0.1
servers: 
    - url: http://localhost:8080
      description: Local dev server
paths:
  /hello/{name}:
    get:
      summary: Echos your input back to you
      description: A simple demo service that simply echos your name.
      parameters: 
        - name: name
          in: path
          required: true
          description: The value you would like to have echoed back to you.
          schema:
            type: string
      responses:
        '200':
          description: The string name sent to the service.
          content:
            application/json:
              schema:
                type: string
    