openapi: 3.0.0
info:
  title: Echo Service
  description: A simple service that echoes your input back to you as a string of corresponding month
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: local dev server
paths:
  /month/{monthNumber}:
    get:
      summary: echoes back a number
      description: converts input number to month string
      parameters: 
      - name: monthNumber
        in: path
        required: true
        description: the value for the month you would like echoed back to you
        schema:
          type: integer
          format: int64
          minimum: 1
          maximum: 12
      responses:
        '200':
          description: the corresponding month
          content:
            application/json:
              schema:
                type: string
        '422':
          description: you must enter a number between 1 and 7
      